# Generated by Django 2.0.1 on 2018-04-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180411_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventownerline',
            name='emailed',
            field=models.BooleanField(default=False, help_text='Guest Invite sent'),
        ),
    ]
