# Generated by Django 2.0.1 on 2018-04-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_eventownerline_emailed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventownerline',
            name='emailed',
        ),
    ]
