# Generated by Django 2.0.1 on 2018-04-16 22:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_eventownerline_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupline',
            name='group_line_key',
            field=models.CharField(default=accounts.models.generate_key, max_length=6),
        ),
    ]
