# Generated by Django 2.0.1 on 2018-01-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(help_text='Enter Event Date and Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(help_text='Enter Event name', max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email_models',
            field=models.EmailField(help_text='Enter Guest email address', max_length=70),
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(help_text='Enter Guest first name', max_length=30),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(help_text='Enter Guest surname', max_length=30),
        ),
    ]
