# Generated by Django 2.0.1 on 2018-01-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_event_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Guest')),
            ],
        ),
    ]
