# Generated by Django 2.0.1 on 2018-01-26 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventline'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_password', models.CharField(max_length=256)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventline',
            options={'verbose_name_plural': 'Pairings'},
        ),
    ]
