# Generated by Django 2.0.1 on 2018-02-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventline_going'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventline',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
