# Generated by Django 2.0.1 on 2018-02-09 03:00

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventline_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_key',
            field=models.CharField(default=event.models.generate_key, max_length=6),
        ),
    ]
