# Generated by Django 2.0.1 on 2018-02-09 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20180209_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpassword',
            name='event_id',
        ),
        migrations.DeleteModel(
            name='EventPassword',
        ),
    ]
