# Generated by Django 2.0.1 on 2018-02-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20180209_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default='not implemented fn', help_text='Enter Guest first name', max_length=30),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default='not implemented sn', help_text='Enter Guest surname', max_length=30),
        ),
    ]
