# Generated by Django 2.0.1 on 2018-02-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20180211_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_creator',
            field=models.CharField(default='John Smith', help_text='Enter Your Name', max_length=75),
        ),
    ]
