# Generated by Django 2.0.1 on 2018-02-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_event_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Guest')),
            ],
        ),
        migrations.AddField(
            model_name='eventline',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
