# Generated by Django 2.0.1 on 2018-02-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20180211_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_public',
            field=models.BooleanField(default=False, help_text='Whether the public can see this'),
        ),
    ]
