# Generated by Django 2.0.1 on 2018-04-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_interestedline_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_creator_id',
            field=models.IntegerField(default=0, help_text='ID'),
        ),
    ]
