# Generated by Django 2.0.1 on 2018-04-10 20:31

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_event_event_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_key',
            new_name='event_private_key',
        ),
        migrations.AddField(
            model_name='event',
            name='event_public_key',
            field=models.CharField(default=event.models.generate_key, max_length=6),
        ),
    ]
