# Generated by Django 2.0.1 on 2018-04-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20180410_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_private_key',
            new_name='event_key',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_public_key',
        ),
    ]
