# Generated by Django 2.0.1 on 2018-04-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20180410_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='email_models',
            new_name='email_address',
        ),
    ]
