# Generated by Django 2.0.1 on 2018-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20180411_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_lifetime',
            field=models.IntegerField(default=10, help_text='Life After Event Time (Days)'),
        ),
    ]
