# Generated by Django 2.0.1 on 2018-04-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_event_event_lifetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventline',
            name='emailed',
            field=models.BooleanField(default=False, help_text='Guest Invite sent'),
        ),
    ]
