# Generated by Django 2.0.1 on 2018-04-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_event_event_maximum_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_state',
            field=models.IntegerField(default=0, help_text='0 - Open, 1 - Paused, 2 - Closed'),
        ),
    ]
