# Generated by Django 2.0.1 on 2018-04-15 14:41

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_event_event_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedline',
            name='interest_key',
            field=models.CharField(default=event.models.generate_key, max_length=6),
        ),
    ]
