# Generated by Django 2.0.1 on 2018-04-15 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_eventviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventviews',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
