# Generated by Django 2.0.1 on 2018-04-15 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20180415_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventline',
            name='response_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
