# Generated by Django 2.0.1 on 2018-04-15 20:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_eventline_response_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('registrations', models.IntegerField(default=0)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventviews',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='eventline',
            name='response_date',
        ),
        migrations.DeleteModel(
            name='EventViews',
        ),
    ]
