# Generated by Django 2.0.1 on 2018-04-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_auto_20180415_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventline',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
