# Generated by Django 2.0.1 on 2018-04-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_eventline_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventline',
            name='going',
        ),
    ]
