# Generated by Django 2.0.1 on 2018-04-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_remove_eventline_going'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='event_paused',
            field=models.BooleanField(default=False),
        ),
    ]
